# Generated by Django 3.1.5 on 2021-01-05 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=50)),
                ('cena_DIN', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stolica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('dimenzije', models.CharField(max_length=50)),
                ('cena_DIN', models.IntegerField(default=0)),
                ('proizvedeno_Od', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.drvo')),
            ],
        ),
    ]
